services:

  postgres:
    image: postgres:15
    container_name: go_pg
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: go_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: go_rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ 通信端口
      - "15672:15672"     # 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  adminer:
    image: adminer
    container_name: go_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
  redis_data:
